### ISSUE TITLE
The sum of percentages

### ISSUE THREAD

**Issue by wangk2014** [natalia-osa/CircleStatus#2]
When the sum of percentages equal 1.0f,  program will crash.（Xcode7.2.1, iOS 9.2）

**Comment by natalia-osa** [comment]
Please update to the new version **1.2.2** (available via CocoaPods).
Fixed in https://github.com/natalia-osa/CircleStatus/commit/238e951ede3445fb91b95b113a51445d27cba8ba.

Hi, I've just updated the code (btw added generics & nullability and few other improvements). The crash happened because of invalid comparison `percentage > 1`, while in fact it could add to more than 1 (because of floating numbers). I've fixed this issue and exchanged assert here to log with a warning that total or single percentage should not exceed 1. Hope it solves the issue, otherwise reopen it please. Thanks for submitting the issue!
